# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='asd', max_length=150),
            preserve_default=False,
        ),
    ]
