# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='slackchat.User'),
            preserve_default=False,
        ),
    ]
