# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0002_reaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='slackchat.Message'),
        ),
    ]
