# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0002_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='api_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='api_id',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
