# Generated by Django 2.0.2 on 2018-02-07 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0002_auto_20180207_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='live',
            field=models.BooleanField(default=False, help_text='May be used by renderer to determine        if it should repoll for messages while chat is live.'),
        ),
        migrations.AddField(
            model_name='channel',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='May be used by renderer to         create dateline.'),
            preserve_default=False,
        ),
    ]
