# Generated by Django 2.0.2 on 2018-02-04 03:17

from django.db import migrations, models
import django.db.models.deletion
import slackchat.conf


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0002_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255)),
                ('character', models.CharField(max_length=100)),
                ('chat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackchat.ChatType')),
                ('role', models.ForeignKey(blank=True, help_text='Restrict this argument to users with a certain role.', null=True, on_delete=django.db.models.deletion.CASCADE, to='slackchat.Role')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('key', models.SlugField(max_length=30)),
                ('value', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kwargs', to='slackchat.Message')),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='chat_type',
        ),
        migrations.RemoveField(
            model_name='action',
            name='role',
        ),
        migrations.RemoveField(
            model_name='key',
            name='message',
        ),
        migrations.RemoveField(
            model_name='key',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='action',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=slackchat.conf.default_upload_to),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Key',
        ),
        migrations.AddField(
            model_name='keywordargument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackchat.User'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='argument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slackchat.Argument'),
        ),
    ]
