# Generated by Django 2.0.2 on 2018-02-07 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0003_auto_20180207_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='May be used by renderer to         create dateline.'),
        ),
    ]
