# Generated by Django 2.0.2 on 2018-02-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0003_auto_20180204_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommessagetemplate',
            name='custom_action',
        ),
        migrations.AddField(
            model_name='custommessagetemplate',
            name='argument_name',
            field=models.SlugField(blank=True, help_text='Add an argument to the message if search_string         is triggered.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='name',
            field=models.SlugField(help_text='The name of the argument that will be attached to a          message.', max_length=255),
        ),
        migrations.AlterField(
            model_name='custommessagetemplate',
            name='content_template',
            field=models.TextField(help_text='A Python format string whose args are the capture groups         from search_string.'),
        ),
        migrations.AlterField(
            model_name='custommessagetemplate',
            name='search_string',
            field=models.CharField(help_text='A regex search string with capture groups.', max_length=255),
        ),
    ]
