# Generated by Django 2.0.2 on 2018-02-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0004_auto_20180204_0739'),
    ]

    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='CustomMessageTemplate',
            new_name='CustomContentTemplate',
        ),
        migrations.RemoveField(
            model_name='custommessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='custommessage',
            name='message_template',
        ),
        migrations.RemoveField(
            model_name='custommessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomMessage',
        ),
    ]
