# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0004_channel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='channel',
            name='api_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
