# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsoneditor.fields.postgres_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0004_auto_20171226_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', jsoneditor.fields.postgres_jsonfield.JSONField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_messages', to='slackchat.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('key', models.SlugField(max_length=30)),
                ('value', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='slackchat.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackchat.User')),
            ],
        ),
        migrations.RenameModel(
            old_name='MessageMarkup',
            new_name='CustomMessageTemplate',
        ),
        migrations.RemoveField(
            model_name='markupcontent',
            name='message',
        ),
        migrations.RemoveField(
            model_name='markupcontent',
            name='message_markup',
        ),
        migrations.RemoveField(
            model_name='markupcontent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='message',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='MarkupContent',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AddField(
            model_name='custommessage',
            name='message_markup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackchat.CustomMessageTemplate'),
        ),
        migrations.AddField(
            model_name='custommessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackchat.User'),
        ),
    ]
