# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0005_auto_20171226_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custommessage',
            old_name='message_markup',
            new_name='message_template',
        ),
        migrations.RenameField(
            model_name='custommessagetemplate',
            old_name='action_tag',
            new_name='custom_action',
        ),
        migrations.RemoveField(
            model_name='custommessagetemplate',
            name='flow',
        ),
        migrations.AddField(
            model_name='chattype',
            name='render_to_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custommessagetemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
