# Generated by Django 2.0.2 on 2018-02-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0005_auto_20180204_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='chat_type',
        ),
        migrations.RemoveField(
            model_name='roleassignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='roleassignment',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='roleassignment',
            name='role',
        ),
        migrations.RemoveField(
            model_name='argument',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RoleAssignment',
        ),
    ]
