# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0006_auto_20171116_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
