# Generated by Django 2.0.2 on 2018-02-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0006_auto_20180210_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='image_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='image_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
