# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0006_auto_20171227_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_message', to='slackchat.Message'),
        ),
    ]
