# Generated by Django 2.0.2 on 2018-02-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0007_auto_20180210_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='service_icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='service_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('message', 'title_link', 'image_url')},
        ),
    ]
