# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0007_auto_20171116_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='api_id',
            field=models.SlugField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
