# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0007_auto_20171227_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('name', models.SlugField(max_length=30)),
                ('value', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='slackchat.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackchat.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='message',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
