# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0008_auto_20171227_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommessage',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='custommessagetemplate',
            name='content_template',
            field=models.TextField(),
        ),
    ]
