# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0009_auto_20171228_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='slackchat.Message'),
        ),
    ]
