# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0012_remove_custommessagetemplate_regex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField()),
                ('verified', models.BooleanField()),
            ],
        ),
    ]
