# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackchat', '0014_auto_20171228_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
